# Generated by Django 5.2.6 on 2025-09-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Shorts', 'shorts'), ('Ball', 'ball'), ('Shoes', 'shoes'), ('Shirts', 'shirts'), ('Hoodies', 'hoodies'), ('Socks', 'socks')], max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveBigIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
