# Generated by Django 5.2.6 on 2025-09-16 02:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Shorts', 'shorts'), ('Ball', 'ball'), ('Shoes', 'shoes'), ('Shirts', 'shirts'), ('Hoodies', 'hoodies'), ('Socks', 'socks')], max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveBigIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
